Provide support to run inside Docker
jceb/mdshow pull request #4
Opened 2021-03-03 10:21 UTC by jurgenhaas

This PR provides:

**New files**

- docker-entrypoint.sh
- Dockerfile
- mdshow.sh: script to run on the host to start the Docker container and run mdshow commands.

**Changes in assets/pandoc/templates/default.revealjs**

Get theme CSS from `.mdshow/theme/...` instead of `$revealjs-url$/theme/...` because that way, custom themes that also provide additional assets and not only a css file are supported.

**Changes in mdshow**

- Switched from yarn to npm
- Changed config path from homedir to `/opt` because otherwise we run into permission issues as the host user is unknown inside the container
- Call `gulp css-themes` once in sync-custom-themes to get a potential custom theme being compiled initially and not only after updates
- Switch arguments in `$(MDSHOW_CONFIG)/reveal.js/dist/theme/%: $(MDSHOW_CONFIG)/theme/%/assets` and also use copy instead of link.
- Add new argument `--chrome-arg="--no-sandbox"` to PDF creation as the chrome process wouldn't launch otherwise.

2021-03-03 17:41 UTC, jceb commented
Does the non-Docker version still work?

2021-03-03 19:14 UTC, jurgenhaas commented
I haven't tried, but it should, the changes are minor with regard to that.

2021-03-04 07:06 UTC, jurgenhaas commented
@jceb Just thinking, we could of course add some context checking to the make script to keep it at its original behaviour on the host and do the docker specific stuff inside.

2021-03-21 19:15 UTC, jceb requested changes

2021-03-21 19:15 UTC, jceb commented on assets/pandoc/templates/default.revealjs
> +  <link rel="stylesheet" href=".mdshow/theme/$theme$/assets/$theme$.css" id="theme">
This looks like an incompatible change, same below.

2021-03-21 19:15 UTC, jceb commented on Dockerfile
> +                libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 \
What are all these x11 libraries needed for?

2021-03-21 19:15 UTC, jceb commented on docker-entrypoint.sh
> +set -e
Please add `set -u` as well.

2021-03-21 19:15 UTC, jceb commented on docker-entrypoint.sh
> +#!/bin/sh
Better use `/bin/bash`

2021-03-21 19:15 UTC, jceb commented on mdshow
> +# NOTE Jürgen Haas: switched from yarn to npm, because yarn does not install node_modules/node-jp/bin
Strange, it does for me on the desktop. Why wouldn't it work in docker? Maybe use a nodeJS docker image instead of ubuntu? I'm a big fan of Alpine which is much smaller than ubuntu images.

2021-03-21 19:15 UTC, jceb commented on Dockerfile
> +RUN echo "Setup MdShow" && \
MdShow => mdshow

2021-03-21 19:15 UTC, jceb commented on mdshow
> +		npm install && npm add node-jq decktape gulp
why add gulp, isn't it part of revealjs already?

2021-03-21 19:15 UTC, jceb commented on mdshow.sh
> +docker run --user=$(id -u) --rm -it --net=host ${THEME} --volume=$(pwd):/mdshow --workdir=/mdshow registry.lakedrops.com/docker/mdshow mdshow $@
Let's move workdir into Dockerfile.

2021-03-21 19:15 UTC, jceb commented on mdshow.sh
> +docker run --user=$(id -u) --rm -it --net=host ${THEME} --volume=$(pwd):/mdshow --workdir=/mdshow registry.lakedrops.com/docker/mdshow mdshow $@
Let's also change the docker repository to `jceb/mdshow` on hub.docker.com

2021-03-21 19:15 UTC, jceb commented on mdshow
> +	@cp $@.css $<
This rule looks broken and it probably breaks compatibility with the non-dockerized version. The assets folder is referenced by the source but it's copied with `cp` without `-r` .. this probably doesn't work.

2021-03-21 19:15 UTC, jceb commented on mdshow
> +MDSHOW_CONFIG = /opt/mdshow
This is an incompatible change when mdshow runs outside docker. Could we mitigate this by adding another variable that's overridden within docker, something along the lines of:

```
CONFIG_PATH = ${HOME}/.config
MDSHOW_CONFIG = $(CONFIG_PATH)/mdshow
```

And then call make with `make <target> CONFIG_PATH=/opt`

2021-03-21 19:15 UTC, jceb commented on mdshow
> +	@[ -n "$^" ] && cd $(MDSHOW_CONFIG)/reveal.js && gulp css-themes || true
Why call gulp manually here, shouldn't it be called by gulp-watch automatically?

2021-03-21 19:15 UTC, jceb commented on docker-entrypoint.sh
> +#!/bin/sh
I haven't fully wrapped my head around this script. What is it good for? Why not use `mdshow` as entrypoint?

2021-03-21 19:15 UTC, jceb commented on mdshow.sh
> +#!/bin/bash
Could we turn this script into a `mdshow` Makefile target, e.g. ? This way the user always calls `mdshow` instead of a separate command.

How about we make the mdshow Makefile aware of docker and add a `DOCKER` variable. When it's set it executes the Makefile targets in the docker container. A call would look like this `mdshow pdf DOCKER=1`. Just a few targets would need to capture and react to it. The majority of the targets wouldn't need to know about it. This could be extended one step further by setting the variable through the name of the command, e.g. if the command is called `dmdshow` then `DOCKER=1` is set.

2021-03-21 19:15 UTC, jceb commented on mdshow.sh
> +docker run --user=$(id -u) --rm -it --net=host ${THEME} --volume=$(pwd):/mdshow --workdir=/mdshow registry.lakedrops.com/docker/mdshow mdshow $@
One last thing, how does the docker integration handle multiple parallel executions of the `mdshow` command? The default mdshow command takes a port to separate multiple executions.

2021-03-21 19:16 UTC, jceb commented
@jurgenhaas hey, sorry for the delay. I didn't realize that I have to request a review. So here are the comments.

2021-03-27 11:17 UTC, jurgenhaas commented on Dockerfile
> +                libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 \
They are required for the PDF creation.

2021-03-27 11:17 UTC, jurgenhaas commented on assets/pandoc/templates/default.revealjs
> +  <link rel="stylesheet" href=".mdshow/theme/$theme$/assets/$theme$.css" id="theme">
Well, even on a host based system I'd suggest to grab assets from the config path rather than from the distro path, because I wouldn't want to copy custom assets like a custom theme into the distro directory. So yes, this changes the location for the assets, but that should work both inside the container and on the host likewise.

2021-03-27 11:17 UTC, jurgenhaas commented on docker-entrypoint.sh
> +#!/bin/sh
Changed

2021-03-27 11:17 UTC, jurgenhaas commented on docker-entrypoint.sh
> +#!/bin/sh
This way you can execute other commands in the container too if you wanted to.

2021-03-27 11:17 UTC, jurgenhaas commented on docker-entrypoint.sh
> +set -e
That would break the test below, which verifies if the DOCKER_HOST variable is available, so we can't add this here.

2021-03-27 11:17 UTC, jurgenhaas commented on mdshow
> +# NOTE Jürgen Haas: switched from yarn to npm, because yarn does not install node_modules/node-jp/bin
I've had that issue on the desktop before and it was most likely because of missing dependencies. So I tried npm instead and that worked. I have no intention to spend more time getting yarn to work as it works just fine with npm.

I use Alpine normally as well, but started here with Ubuntu because I wanted to replicate my hosts environment. For now, I wouldn't want to spend more time trying to resolve dependencies again, just to save a few bytes - although I otherwise agree with your statement.

2021-03-27 11:17 UTC, jurgenhaas commented on mdshow
> +MDSHOW_CONFIG = /opt/mdshow
Good idea, I've added the CONFIG_PATH variable to the mdshow script so that it'll always be used.

2021-03-27 11:17 UTC, jurgenhaas commented on mdshow
> +		npm install && npm add node-jq decktape gulp
It wasn't, I had to install it separately.

2021-03-27 11:17 UTC, jurgenhaas commented on mdshow
> +	@[ -n "$^" ] && cd $(MDSHOW_CONFIG)/reveal.js && gulp css-themes || true
During initial startup, the gulp watch is too late to compile the custom theme which doesn't come with a css but only the SCSS file.

2021-03-27 11:17 UTC, jurgenhaas commented on mdshow
> +	@cp $@.css $<
Well, the link certainly didn't work. Copying the files was the only way to get it to work and I don't see why that should break the host version of mdshow.

2021-03-27 11:17 UTC, jurgenhaas commented on mdshow.sh
> +#!/bin/bash
The makefile is currently completely encapsulated in the container and not accessible from the host. This script file is not even required, it's just a shortcut. People can use this or have their own trigger command in the host. But at least, this is the only thing that needs to b distributed and I prefer that to be as small as possible. Everything else is loaded automatically as t is contained in the docker image.

2021-03-27 11:17 UTC, jurgenhaas commented on mdshow.sh
> +docker run --user=$(id -u) --rm -it --net=host ${THEME} --volume=$(pwd):/mdshow --workdir=/mdshow registry.lakedrops.com/docker/mdshow mdshow $@
Moved.

2021-03-27 11:17 UTC, jurgenhaas commented on mdshow.sh
> +docker run --user=$(id -u) --rm -it --net=host ${THEME} --volume=$(pwd):/mdshow --workdir=/mdshow registry.lakedrops.com/docker/mdshow mdshow $@
That works with the Docker version too, the same PORT argument can be used for this in that context as well.

2021-03-27 11:17 UTC, jurgenhaas commented on mdshow.sh
> +docker run --user=$(id -u) --rm -it --net=host ${THEME} --volume=$(pwd):/mdshow --workdir=/mdshow registry.lakedrops.com/docker/mdshow mdshow $@
Changed.

2021-03-27 11:19 UTC, jurgenhaas commented
@jceb worked on your review and committed the changes.

2021-05-15 06:51 UTC, closed without merging